### ISSUE TITLE
cannot find bunyan and micro-request-bunyan

### ISSUE THREAD

**Issue by pratiks** [TheNoim/fastify-loader#10]
Fastify: 1.13.4
Node: 10 LTS
Loader Version: 2.3.6

I am unable to run the loader for a directory that is two-levels deep.  

The error cited is two fold:  

1. cannot find module bunyan 
2. cannot find module micro-bunyan-request

After I manually satisfy those requirements.  

I get this error: 

``
/Users/pshah/Projects/wavey/wavvy-tenants-api/node_modules/vm2/lib/main.js:430
                        throw this._internal.Decontextify.value(e);
                        ^
VMError: Cannot find module '../routes/auth.js'
```

Let me know if I can help in another way.

**Comment by TheNoim** [comment]
Hey, could you upload an example project where you reproduce the issue?

**Comment by pratiks** [comment]
Please ignore.  I am sorry, this was user error. 

Closing out!
